# Generated by Django 5.0.6 on 2024-10-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='period',
            name='execution_count',
            field=models.SmallIntegerField(default=0, verbose_name='Количество выполнений'),
        ),
    ]
