# Generated by Django 5.0.6 on 2024-10-31 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_alter_task_options_period_execution_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New_model',
        ),
    ]
